### PR TITLE
[1.x] add outputs section, produce both jupyter_scheduler and jupyter-scheduler packages

### PR DESCRIPTION
**Pull request by andrii-i**
Backports https://github.com/conda-forge/jupyter_scheduler-feedstock/pull/5 to 1.x

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andrii-i** [comment]
@conda-forge-admin, please rerender

**Comment by andrii-i** [comment]
@conda-forge-admin, please rerender

**Comment by andrii-i** [comment]
@conda-forge-admin, please rerender

**Comment by andrii-i** [comment]
@conda-forge-admin, please rerender

**Comment by andrii-i** [comment]
Adding `outputs` section to this recipe also brought unexpected errors that are not happening when `outputs` section is absent. Example: [failed build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=803038&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1573). 

As it is evident from the build logs, system is trying to build `zmq` library and is missing `c++` compiler required for it. [Adding generic c++ compiler as a requirement for host environment](https://github.com/conda-forge/jupyter_scheduler-feedstock/pull/10/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR22) solves the problem. 

c++ compiler is actually used in the build process, it’s not just a dependency. That’s why `error_overlinking` being `false` in `conda-forge.yml`, adding `libzmq.so.5` to `missing_dso_whitelist` doesn’t help ([attempt](https://github.com/conda-forge/jupyter_scheduler-feedstock/pull/11/commits/b1a1c5570d4dc73dbe73b97beac69fb2275ca9be)).

**Review by dlqqq — APPROVED** [review]
Great work debugging and determining the need to specify a C++ compiler explicitly. 👍

**Comment by andrii-i** [comment]
Thank you @dlqqq

**Pull request merged**
